version: '3.1'

services:
  postgres:
    container_name: tccDbVitor
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "8001:5432"


volumes:
  postgres-vol: